version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      REDIS_URL: redis://redis:6379
  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/geolocator
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis

volumes:
  redis:
  postgres:
